spring:
  application:
    name: rephub-backend
  mongodb:
    uri: ${MONGO_URI}
    database: rephub
  security:
    user:
      name: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
# jwt
jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000 # 1 hour in milliseconds

